# https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples
version: '3'
services:

  nginx:
    image: nginx:stable #nginx:alpine
    volumes:
      - "./docker-swarm/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./logs/nginx:/var/log/nginx"
      - "./wordpress:/var/www/html/public"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
networks:
  frontend:
