# https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples
version: "3"
services:

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
      - "3000:443"
    networks:
      - frontend
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  frontend:
