# https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples
version: '3'
services:
  wordpress:
    image: wordpress:4.9-php7.2-fpm
    # ports:
        # - '9000:9000'
    volumes:
        # - wordpress-code:/var/www/html
        - ${PWD}/code/wordpress.4.9:/var/www/html
        # - "${PWD}/code/wp-content:/var/www/html/wp-content"
        # - "${PWD}/uploads:/var/www/html/wp-content/uploads"
    environment:
        - WORDPRESS_DB_NAME=wpdbs
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=database
        - WORDPRESS_DB_PASSWORD=aqwe123
    networks:
        - frontend
        - backend
    depends_on:
        - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  database:
    image: mariadb:latest
    # ports:
        # - '3306:3306'
    volumes:
        - mariadb-data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    networks:
        - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
volumes:
  mariadb-data:
  # wordpress-code:

networks:
  frontend:
  backend:
