# https://docs.docker.com/compose/compose-file/#compose-file-structure-and-examples
version: '3'
services:
  nginx:
    image: nginx:stable #nginx:alpine
    volumes:
        - "${PWD}/docker-swarm/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        - "${PWD}/code/wordpress.4.9:/var/www/html"
        - "${PWD}/logs/nginx:/var/log/nginx"
    ports:
        - "80:80"
        - "443:443"
    networks:
        - frontend
    depends_on:
        - wordpress
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  wordpress:
    image: wordpress:4.9-php7.2-fpm
    # ports:
        # - '9000:9000'
    volumes:
        - "${PWD}/code/wordpress.4.9:/var/www/html"
    environment:
        - WORDPRESS_DB_NAME=wpdbs
        - WORDPRESS_TABLE_PREFIX=wp_
        - WORDPRESS_DB_HOST=database
        - WORDPRESS_DB_PASSWORD=aqwe123
    networks:
        - frontend
        - backend
    depends_on:
        - database
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  database:
    image: mariadb:latest
    # ports:
        # - '3306:3306'
    volumes:
        - "./mariadb_data:/var/lib"
    environment:
        - MYSQL_ROOT_PASSWORD=aqwe123
    networks:
        - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    networks:
      - backend
    depends_on:
      - database
    environment:
        - PMA_ARBITRARY=1
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  frontend:
  backend:
